name = "Chatterjee"
uuid = "d027f803-c390-4558-9fc1-16fb14c1dcef"
authors = ["h-spiess <spiess.heiner@gmail.com> and contributors"]
version = "0.1.0"

[deps]
RollingFunctions = "b0e4dd01-7b14-53d8-9b45-175a3e362653"

[compat]
RollingFunctions = "0.6"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
